### PR TITLE
[+] Optional response argument in i18nRouter()

### PR DESCRIPTION
**Pull request by Nitlix**
Allowing for a custom response object to be parsed, so information could be shared between different libraries if they also make use of the response object.

### CODE REVIEW

**Review by i18nexus — CHANGES_REQUESTED** [review]
For the typing, is there a reason you used:

`response: null | NextResponse = null`

instead of simply:

`response?: NextResponse`

If not, can you please use the latter?

**Comment by Nitlix** [comment]
That's true, I've updated it just now 👍

**Comment by Nitlix** [comment]
Hey again! Have you noticed my change?

**Comment by i18nexus** [comment]
Hey! Yes, thanks for making the change. This will be merged and released with version 3.1.2 by the end of the day.

**Comment by Nitlix** [comment]
No worries, hope everything goes well!👍

**Pull request merged**
